substitutions:
  device_name: desk32
  name: desk32
  min_height: "28.1" #"73.6" # Min height + 0.1
  max_height: "46.9" #"122.9" # Max height - 0.1
  
esphome:
  name: ${name}
  comment: ${device_name}
  platform: esp32 # TODO Change to your platform
  board: esp32dev # TODO Change to your board
  includes:
  - desk_height_sensor.h
  - desk_keypad.h

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:
  
web_server:
  port: 80

script:
  - id: screen_timer
    mode: restart
    then:
     # on_start
     - logger.log: "Executing screen timer command"
     - switch.turn_on: virtual_screen
     - lambda: |-
          id(backlight).publish_state(true);
     - delay: 12s  # timer length (keypad screen timeout is 10s + 2s buffer)
     - if:
        condition:
         binary_sensor.is_off : screen
        then:
        - switch.turn_off: virtual_screen
        - lambda: |-
            id(backlight).publish_state(false);
     # on_end

  - id: script_start_command
    mode: restart
    then:
     - logger.log: "Executing Empty command"
     - if:
        condition:
         switch.is_off : virtual_screen
        then:
          - script.execute: screen_timer
          - delay: 480ms
        else:
          - script.execute: screen_timer
          - delay: 480ms
    
uart:
  - id: desk_uart
    baud_rate: 9600
    tx_pin: GPIO17
    rx_pin: GPIO16
  - id: keypad_uart
    baud_rate: 9600
    tx_pin: GPIO26 #GPIO1
    rx_pin: GPIO25 #GPIO3
    debug:
      direction: TX

# Example configuration entry for ESP32
i2c:
  sda: 21
  scl: 22
  scan: true

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: Uptime

  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: knob
    internal: true
    pin_a: 
      number: GPIO13
      mode:
        input: true
        pullup: true
    pin_b: 
      number: GPIO5
      mode: 
        input: true
        pullup: true
    filters:
    - debounce: 0.25s
    on_clockwise:
    - logger.log: "Turned Clockwise"
    - script.execute: script_start_command
    - switch.turn_on: switch_up
    - delay: 108ms
    on_anticlockwise:
    - logger.log: "Turned Anticlockwise"
    - script.execute: script_start_command
    - switch.turn_on: switch_down
    - delay: 108ms

  - platform: custom
    lambda: |-
      auto desk_height_sensor = new DeskHeightSensor(id(desk_uart));
      App.register_component(desk_height_sensor);
      return {desk_height_sensor};
    sensors:
      id: "desk_height"
      name: Desk Height
      unit_of_measurement: in
      accuracy_decimals: 1
      icon: "mdi:counter"
      on_value:
        then:
          - script.execute: screen_timer
          # - cover.template.publish:
          #    id: desk
          #    position: !lambda |-
          #        // The sensor outputs values from min_height (cm) to max_height (cm)
          #        // We need to translate this to 0 - 1 scale.
          #        float position = (float(x) - float(${min_height})) / (float(${max_height}) - float(${min_height}));
          #        return position;

  - platform: custom
    lambda: |-
      auto desk_keypad_sensor = new DeskKeypad(id(keypad_uart));
      App.register_component(desk_keypad_sensor);
      return {desk_keypad_sensor};
    sensors:
      id: "desk_command"
      name: Desk command
      icon: "mdi:counter"
      on_value:
        then:
          lambda: |-
            if(!id(keypad_switch).state)
            {
              if(id(desk_command).state == 1)
              {
                id(desk).make_call().set_command_open();
              } else if(id(desk_command).state == 2)
              {
                id(desk).make_call().set_command_close();
              } else if(id(desk_command).state == 3)
              {
                id(switch_preset1).turn_on();
              } else if(id(desk_command).state == 4)
              {
                id(switch_preset2).turn_on();
              } else if(id(desk_command).state == 5)
              {
                id(switch_preset3).turn_on();
              }  else if(id(desk_command).state == 6)
              {
                id(switch_m).turn_on();
              } else if(id(desk_command).state == 7)
              {
                id(switch_alarm).turn_on();
              } else if(id(desk_command).state == 8)
              {
                id(desk).make_call().set_command_stop();
              }
            }
binary_sensor:
  - platform: gpio
    name: "Screen"
    id: "screen"
    pin: GPIO27 #GPIO22
    internal: true
    on_press:
      then:
        - switch.turn_on: virtual_screen
    on_release:
      then:
        - switch.turn_off: virtual_screen

  - platform: gpio
    name: "Multi-Click Button"
    id: click
    pin: 
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - lambda: |-
            id(backlight).publish_state(true);
            id(backlight).publish_state(false);
    on_multi_click: 
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Triple Clicked"
          - switch.turn_on: switch_preset2      
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - switch.turn_on: switch_preset1
      - timing:
          - ON for 1s to 2s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - script.execute: script_start_command
      - timing: 
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - script.execute: script_start_command

  - platform: template
    id: backlight
    filters:
      - delayed_off: 10s
    on_press:
      then:
        - lambda: |-
            id(mydisplay).backlight();
    on_release:
      then:
        - lambda: |-
            id(mydisplay).no_backlight();

switch:
  - platform: template
    name: "Keypad locked"
    icon: mdi:key
    id: "keypad_switch"
    internal: true
    restore_state: true
    assumed_state: false
    optimistic: true

  - platform: template
    name: "Preset 1"
    id: switch_preset1
    icon: mdi:numeric-1-box
    turn_on_action:
     - logger.log: "Executing Preset 1 command"
     - script.execute: script_start_command
     - script.wait: script_start_command
     - uart.write:
         id: desk_uart
         data: [0x9b, 0x06, 0x02, 0x04, 0x00, 0xac, 0xa3, 0x9d]
    internal: false

  - platform: template
    name: "Preset 2"
    id: switch_preset2
    icon: mdi:numeric-2-box
    turn_on_action:
     - logger.log: "Executing Preset 2 command"
     - script.execute: script_start_command
     - script.wait: script_start_command
     - uart.write:
         id: desk_uart
         data: [0x9b, 0x06, 0x02, 0x08, 0x00, 0xac, 0xa6, 0x9d]
    internal: false

  - platform: template
    name: "Preset 3"
    id: switch_preset3
    icon: mdi:numeric-3-box
    turn_on_action:
     - logger.log: "Executing Preset 3 command"
     - script.execute: script_start_command
     - script.wait: script_start_command
     - uart.write:
         id: desk_uart
         data: [0x9b, 0x06, 0x02, 0x10, 0x00, 0xac, 0xac, 0x9d]
    internal: false

  - platform: template
    name: "M"
    id: switch_m
    icon: mdi:alpha-m-circle
    turn_on_action:
     - logger.log: "Executing Preset 3 command"
     - script.execute: script_start_command
     - script.wait: script_start_command
     - uart.write:
         id: desk_uart
         data: [0x9b, 0x06, 0x02, 0x20, 0x00, 0xac, 0xb8, 0x9d]
    internal: false

  - platform: template
    name: "Alarm"
    id: switch_alarm
    icon: mdi:alpha-m-circle
    turn_on_action:
     - logger.log: "Executing Alarm command"
    #  - script.execute: script_start_command
    #  - script.wait: script_start_command
    #  - uart.write:
    #      id: desk_uart
    #      data: [0x9b, 0x06, 0x02, 0x40, 0x00, 0xac, 0x90, 0x9d]
    internal: true

  - platform: gpio
    name: "Screen"
    id: "virtual_screen"
    pin:
      number: GPIO23
      mode: OUTPUT
    restore_mode: ALWAYS_ON
    internal: false

  - platform: uart
    name: "Up"
    id: switch_up
    icon: mdi:arrow-up-bold
    data: [0x9b, 0x06, 0x02, 0x01, 0x00, 0xfc, 0xa0, 0x9d]
    uart_id: desk_uart
    internal: true
    

  - platform: uart
    name: "Down"
    id: switch_down
    icon: mdi:arrow-down-bold
    data: [0x9b, 0x06, 0x02, 0x02, 0x00, 0x0c, 0xa0, 0x9d]
    uart_id: desk_uart
    internal: true

  - platform: uart
    name: "Empty command"
    id: switch_empty
    data: [0x9b, 0x06, 0x02, 0x00, 0x00, 0x6c, 0xa1, 0x9d]
    uart_id: desk_uart
    internal: true

cover:
  - platform: template
    name: "Desk"
    id: "desk"
    assumed_state: true
    # has_position: true
    # position_action:
    #   - logger.log: "Requesting action change"

    # Move desk up
    open_action:
      - script.execute: script_start_command
      - script.wait: script_start_command
      - while:
          condition:
            sensor.in_range:
              id: desk_height
              below: ${max_height}
          then:
          - logger.log: "Executing up command"
          # - cover.template.publish:
          #     id: desk
          #     current_operation: OPENING
          - switch.turn_on: switch_up
          - delay: 108ms
          
          
    
    # Move desk down
    close_action:
      - script.execute: script_start_command
      - script.wait: script_start_command
      - while:
          condition:
            sensor.in_range:
              id: desk_height
              above: ${min_height} 
          then:
          - logger.log: "Executing down command"
          # - cover.template.publish:
          #     id: desk
          #     current_operation: CLOSING
          - switch.turn_on: switch_down
          - delay: 108ms

   
    optimistic: true

display:
  - platform: lcd_pcf8574
    id: mydisplay
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.printf("Desk: %.1f in", id(desk_height).state);
      it.print(0,1,id(text).state);

text_sensor:
  - platform: homeassistant
    name: "HA Sensor Status"
    id: text
    entity_id: device_tracker.somesensor
